(setq inhibit-startup-screen t)
(menu-bar-mode 0)
(tool-bar-mode 0)
(ido-mode 1)
(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/"))
(add-hook 'after-init-hook 'global-company-mode)
(setq company-idle-delay 0)
(setq company-minimum-prefix-length 2)
(if (version<= "26.0.50" emacs-version)
    (global-display-line-numbers-mode)
  (global-linum-mode))
(add-to-list 'auto-mode-alist `(,(rx ".js" string-end) . js2-mode))
